export const LISTINGS_REQUEST = '[Listings] LISTINGS_REQUEST';
export const LISTINGS_SUCCESS = '[Listings] LISTINGS_SUCCESS';
export const LISTINGS_FAILURE = '[Listings] LISTINGS_FAILURE';

export const LISTING_CREATE_REQUEST = '[Listings] LISTING_CREATE_REQUEST';
export const LISTING_CREATE_SUCCESS = '[Listings] LISTING_CREATE_SUCCESS';
export const LISTING_CREATE_FAILURE = '[Listings] LISTING_CREATE_FAILURE';
